class ChatViemModel {
  ChatViemModel._();
  static final ChatViemModel instance = ChatViemModel._();

  var userList = [
    'Shabbir',
    'Sagir',
    'Zahir',
    'Adnan',
    'Zohan',
  ];

  var chatList = [
    {
      'text': 'Hi',
      'isSender': false,
      'sent': false,
      'delivered': false,
      'seen': false,
      'date': '2024-01-04',
    },
    {
      'text': 'Hello',
      'isSender': true,
      'sent': true,
      'delivered': true,
      'seen': true,
      'date': '2024-01-04',
    },
    {
      'text': 'how are you',
      'isSender': true,
      'sent': true,
      'delivered': true,
      'seen': true,
      'date': '2024-01-04',
    },
    {
      'text': '',
      'isSender': false,
      'sent': false,
      'delivered': true,
      'seen': true,
      'date': '2024-01-05',
    },
    {
      'text': 'I am good',
      'isSender': false,
      'sent': false,
      'delivered': false,
      'seen': false,
      'date': '2024-01-05',
    },
    {
      'text': 'What about you?',
      'isSender': false,
      'sent': false,
      'delivered': false,
      'seen': false,
      'date': '2024-01-05',
    },
    {
      'text': '',
      'isSender': false,
      'sent': false,
      'delivered': true,
      'seen': true,
      'date': '2024-01-06',
    },
    {
      'text': 'I am also good',
      'isSender': true,
      'sent': true,
      'delivered': true,
      'seen': true,
      'date': '2024-01-06',
    },
    {
      'text': 'And',
      'isSender': true,
      'sent': true,
      'delivered': true,
      'seen': false,
      'date': '2024-01-06',
    },
    {
      'text': 'What are you doing?',
      'isSender': true,
      'sent': true,
      'delivered': false,
      'seen': false,
      'date': '2024-01-06',
    },
    {
      'text': '',
      'isSender': false,
      'sent': false,
      'delivered': true,
      'seen': true,
      'date': '2024-01-07',
    },
    {
      'text': 'nothing',
      'isSender': false,
      'sent': false,
      'delivered': false,
      'seen': false,
      'date': '2024-01-07',
    },
    {
      'text': 'hey',
      'isSender': true,
      'sent': false,
      'delivered': false,
      'seen': false,
      'date': '2024-01-07',
    },
    {
      'text': 'hello',
      'isSender': true,
      'sent': false,
      'delivered': false,
      'seen': false,
      'date': '2024-01-07',
    },
    {
      'text': 'kya hua',
      'isSender': true,
      'sent': false,
      'delivered': false,
      'seen': false,
      'date': '2024-01-07',
    },
  ];
}
